# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  run:
    deps: [run-backend, run-frontend]
    silent: true
    
  run-backend:
    cmds:
      - cd backend && go run cmd/main/main.go
    silent: true
  
  run-frontend:
    cmds:
      - cd frontend && bun dev
    silent: true