# https://taskfile.dev

version: '3'

tasks:
  backend:
    dir: '{{.USER_WORKING_DIR}}/backend'
    cmds:
      - go run cmd/main/main.go
    silent: true
  
  frontend:
    dir: '{{.USER_WORKING_DIR}}/frontend'
    cmds:
      - bun dev
    silent: true

  default:
    deps: [backend, frontend]
    silent: true
