# https://taskfile.dev

version: "3"

tasks:
  backend:
    dir: "{{.USER_WORKING_DIR}}/backend"
    cmds:
      - go run cmd/main/main.go
    silent: true

  frontend:
    dir: "{{.USER_WORKING_DIR}}/frontend"
    cmds:
      - bun dev
    silent: true

  build:
    cmds:
      - podman build -t cozy-player .

  login:
    cmds:
      - podman login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD

  push:
    cmds:
      - podman push cozy-player docker://docker.io/skilletfun/cozy-player

  default:
    deps: [backend, frontend]
    silent: true
