# Generated by Django 5.2 on 2025-05-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("tracks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "artists",
                    models.ManyToManyField(
                        related_name="playlists", to="artists.artist"
                    ),
                ),
                (
                    "tracks",
                    models.ManyToManyField(related_name="playlists", to="tracks.track"),
                ),
            ],
        ),
    ]
